# Portfolio Metrics Extraction — Demo

Runs the pipeline over the sample PDF folder and reviews the outputs.
See [specs/spec.md](specs/spec.md) for design rationale and the README for the pipeline diagram.

In [1]:
# 1. Run the pipeline (requires OPENAI_API_KEY in .env)
PDF_FOLDER = "/path/to/pdf-folder"  # <- set me
# !python -m src.pipeline --input {PDF_FOLDER}

In [2]:
# 2. The fact table — every row traceable to file + page + verbatim label
import pandas as pd
metrics = pd.read_csv("output/metrics_long.csv")
metrics.head(15)

,company,company_as_reported,canonical_metric,verbatim_label,value,unit,currency,quarter,year,period_basis,source_file,source_type,report_period,page,location,note,non_canonical,superseded
0,ApexFreight,Apex Freight Solutions Inc.,NaN,Completed Shipments,1.28M,M,NaN,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,NaN,True,False
1,ApexFreight,Apex Freight Solutions Inc.,NaN,Active Shippers,"3,460",count,NaN,2.0,2025.0,point_in_time,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,NaN,True,False
2,ApexFreight,Apex Freight Solutions Inc.,NaN,Active Carriers,"7,900",count,NaN,2.0,2025.0,point_in_time,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,NaN,True,False
3,ApexFreight,Apex Freight Solutions Inc.,NaN,On-Time Delivery Rate,96.1%,%,NaN,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,Carrier-reported with a 48-hour grace window p...,True,False
4,ApexFreight,Apex Freight Solutions Inc.,NaN,Average Take Rate,11.2%,%,NaN,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,NaN,True,False
5,ApexFreight,Apex Freight Solutions Inc.,revenue,Recognized Revenue (transaction),8.6M,M,USD,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,Disclosed separately for the first time in Q2 ...,False,False
6,ApexFreight,Apex Freight Solutions Inc.,NaN,SaaS Tool Fee Revenue,0.7M,M,USD,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,Disclosed separately for the first time in Q2 ...,True,False
7,ApexFreight,Apex Freight Solutions Inc.,revenue,Total Recognized Revenue,9.3M,M,USD,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,NaN,False,False
8,ApexFreight,Apex Freight Solutions Inc.,gross_margin,Gross Margin,54%,%,NaN,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,Expanded to 54%.,False,False
9,ApexFreight,Apex Freight Solutions Inc.,NaN,Marketing Spend as % of Revenue,16%,%,NaN,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,NaN,True,False
10,ApexFreight,Apex Freight Solutions Inc.,NaN,"Support Tickets / 1,000 Shipments",14.3,count,NaN,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,NaN,True,False
11,ApexFreight,Apex Freight Solutions Inc.,headcount,Total Headcount,204,count,NaN,2.0,2025.0,point_in_time,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,table,NaN,False,False
12,ApexFreight,Apex Freight Solutions Inc.,NaN,Contribution Margin per Shipment,$2.30,NaN,USD,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,commentary,Discussed in commentary; not separately tabled.,True,False
13,ApexFreight,Apex Freight Solutions Inc.,NaN,One-time warehouse exit cost,0.6M,M,USD,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,footnote,Q2 2025 only.,True,False
14,ApexFreight,Apex Freight Solutions Inc.,NaN,Non-cash depreciation and amortisation,0.9M,M,USD,2.0,2025.0,quarterly,ApexFreight_Q2_2025.pdf,standalone,Q2 2025,1,footnote,NaN,True,False

In [3]:
# 3. Companies x quarters — the human-review view
pd.read_csv("output/pivot.csv")

,company,canonical_metric,Q2 2024,Q3 2024,Q4 2024,Q1 2025,Q2 2025
0,ApexFreight,gross_margin,NaN,NaN,51%,52%,54%
1,ApexFreight,headcount,NaN,NaN,196,199,204
2,ApexFreight,revenue,NaN,NaN,9.0M,8.9M,8.6M | 9.3M
3,CarbonTrack,arr,NaN,NaN,NaN,$15.2M,$16.9M
4,CarbonTrack,gross_margin,NaN,NaN,NaN,72%,73%
5,CarbonTrack,headcount,NaN,NaN,NaN,72,78
6,CarbonTrack,net_revenue_retention,NaN,NaN,NaN,118%,121%
7,CarbonTrack,revenue,NaN,NaN,NaN,$3.8M,$4.1M
8,ClearPay,gross_margin,NaN,NaN,NaN,66%,67%
9,ClearPay,headcount,NaN,NaN,NaN,203,211
10,ClearPay,revenue,NaN,NaN,NaN,$16.1M,$17.3M
11,ConstructIQ,arr,NaN,NaN,NaN,$17.1M,$18.6M
12,ConstructIQ,gross_margin,NaN,NaN,NaN,70%,71%
13,ConstructIQ,headcount,NaN,NaN,NaN,84,89
14,ConstructIQ,net_revenue_retention,NaN,NaN,NaN,110%,112%
15,ConstructIQ,revenue,NaN,NaN,NaN,$4.2M,$4.5M
16,LendBridge,gross_margin,58%,59%,60%,61%,62%
17,LendBridge,headcount,162,169,175,182,188
18,LendBridge,revenue,$10.1M,$10.8M,$11.4M,$12.1M,$12.7M
19,MediSight,arr,NaN,NaN,24.5M,26.1M,27.9M
20,MediSight,gross_margin,NaN,NaN,75%,76%,77%
21,MediSight,headcount,NaN,NaN,108,114,121
22,MediSight,revenue,NaN,NaN,6.1M,6.3M,6.8M
23,NovaCloud,arr,$24.1M,$26.8M,$29.1M,$31.6M,$34.2M
24,NovaCloud,gross_margin,74%,75%,76%,77%,78%
25,NovaCloud,headcount,112,120,128,135,142
26,NovaCloud,net_revenue_retention,115%,117%,119%,121%,123%
27,NovaCloud,revenue,$5.8M,$6.5M,$7.2M,$7.9M,$8.4M
28,PeopleFlow,arr,NaN,NaN,18.3M,19.8M,21.4M
29,PeopleFlow,gross_margin,NaN,NaN,74%,74%,73%
30,PeopleFlow,headcount,NaN,NaN,88,92,96
31,PeopleFlow,net_revenue_retention,NaN,NaN,116%,117%,118%
32,PeopleFlow,revenue,NaN,NaN,4.4M,4.6M,5.1M
33,TalentVault,arr,NaN,NaN,NaN,$20.8M,$22.4M
34,TalentVault,gross_margin,NaN,NaN,NaN,75%,76%
35,TalentVault,headcount,NaN,NaN,NaN,97,103
36,TalentVault,net_revenue_retention,NaN,NaN,NaN,116%,119%
37,TalentVault,revenue,NaN,NaN,NaN,$5.1M,$5.5M

In [4]:
# 4. What the pipeline is NOT sure about
pd.read_csv("output/flags.csv").sort_values("severity")

,severity,source_file,company,metric,period,detail
0,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,arr,Q2 2025,reported in 2 sources ['CarbonTrack_Q2_2025.pd...
25,info,NovaCloud_Q2_2025.pdf,NovaCloud,revenue,Q2 2025,reported in 2 sources ['NovaCloud_Q2_2025.pdf'...
26,info,NovaCloud_Q2_2025.pdf,NovaCloud,arr,Q2 2025,snapshot and standalone report agree
27,info,NovaCloud_Q2_2025.pdf,NovaCloud,cash,Q2 2025,snapshot and standalone report agree
29,info,NovaCloud_Q2_2025.pdf,NovaCloud,headcount,Q2 2025,snapshot and standalone report agree
30,info,NovaCloud_Q2_2025.pdf,NovaCloud,logo_churn,Q2 2025,snapshot and standalone report agree
31,info,NovaCloud_Q2_2025.pdf,NovaCloud,net_revenue_retention,Q2 2025,snapshot and standalone report agree
32,info,NovaCloud_Q2_2025.pdf,NovaCloud,revenue,Q2 2025,snapshot and standalone report agree
33,info,NovaCloud_Q3_2024.pdf,NovaCloud,revenue,Q3 2024,same value restated under multiple labels/loca...
34,info,PeopleFlow_Q1_2025.pdf,PeopleFlow,gross_margin,Q1 2025,reported in 2 sources ['PeopleFlow_Q1_2025.pdf...
24,info,NovaCloud_Q2_2025.pdf,NovaCloud,net_revenue_retention,Q2 2025,reported in 2 sources ['NovaCloud_Q2_2025.pdf'...
35,info,PeopleFlow_Q1_2025.pdf,PeopleFlow,revenue,Q1 2025,reported in 2 sources ['PeopleFlow_Q1_2025.pdf...
37,info,Portfolio_Snapshot_Q2_2025.pdf,TalentVault,arr,Q2 2025,reported in 2 sources ['Portfolio_Snapshot_Q2_...
38,info,Portfolio_Snapshot_Q2_2025.pdf,TalentVault,gross_margin,Q2 2025,reported in 2 sources ['Portfolio_Snapshot_Q2_...
39,info,Portfolio_Snapshot_Q2_2025.pdf,TalentVault,net_revenue_retention,Q2 2025,reported in 2 sources ['Portfolio_Snapshot_Q2_...
40,info,Portfolio_Snapshot_Q2_2025.pdf,TalentVault,revenue,Q2 2025,reported in 2 sources ['Portfolio_Snapshot_Q2_...
41,info,Portfolio_Snapshot_Q2_2025.pdf,TalentVault,arr,Q2 2025,snapshot and standalone report agree
42,info,Portfolio_Snapshot_Q2_2025.pdf,TalentVault,gross_margin,Q2 2025,snapshot and standalone report agree
43,info,Portfolio_Snapshot_Q2_2025.pdf,TalentVault,net_revenue_retention,Q2 2025,snapshot and standalone report agree
44,info,Portfolio_Snapshot_Q2_2025.pdf,TalentVault,revenue,Q2 2025,snapshot and standalone report agree
45,info,TalentVault_Q2_2025.pdf,TalentVault,NaN,Q2 2025,"verbatim_label 'Two large ATS vendors' found, ..."
36,info,PeopleFlow_Q2_2025.pdf,PeopleFlow,arr,Q2 2025,same value restated under multiple labels/loca...
23,info,NovaCloud_Q2_2025.pdf,NovaCloud,logo_churn,Q2 2025,reported in 2 sources ['NovaCloud_Q2_2025.pdf'...
28,info,NovaCloud_Q2_2025.pdf,NovaCloud,gross_margin,Q2 2025,snapshot and standalone report agree
21,info,NovaCloud_Q2_2025.pdf,NovaCloud,gross_margin,Q2 2025,reported in 2 sources ['NovaCloud_Q2_2025.pdf'...
1,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,gross_margin,Q2 2025,reported in 2 sources ['CarbonTrack_Q2_2025.pd...
2,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,headcount,Q2 2025,reported in 2 sources ['CarbonTrack_Q2_2025.pd...
3,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,net_burn,Q2 2025,reported in 2 sources ['CarbonTrack_Q2_2025.pd...
4,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,net_revenue_retention,Q2 2025,reported in 2 sources ['CarbonTrack_Q2_2025.pd...
5,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,revenue,Q2 2025,reported in 2 sources ['CarbonTrack_Q2_2025.pd...
22,info,NovaCloud_Q2_2025.pdf,NovaCloud,headcount,Q2 2025,reported in 2 sources ['NovaCloud_Q2_2025.pdf'...
7,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,gross_margin,Q2 2025,snapshot and standalone report agree
8,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,headcount,Q2 2025,snapshot and standalone report agree
9,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,net_revenue_retention,Q2 2025,snapshot and standalone report agree
10,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,revenue,Q2 2025,snapshot and standalone report agree
6,info,CarbonTrack_Q2_2025.pdf,CarbonTrack,arr,Q2 2025,snapshot and standalone report agree
12,info,MediSight_Q2_2025.pdf,MediSight,gross_margin,Q2 2025,reported in 2 sources ['MediSight_Q2_2025.pdf'...
13,info,MediSight_Q2_2025.pdf,MediSight,headcount,Q2 2025,reported in 2 sources ['MediSight_Q2_2025.pdf'...
14,info,MediSight_Q2_2025.pdf,MediSight,revenue,Q2 2025,reported in 2 sources ['MediSight_Q2_2025.pdf'...
15,info,MediSight_Q2_2025.pdf,MediSight,arr,Q2 2025,snapshot and standalone report agree
16,info,MediSight_Q2_2025.pdf,MediSight,gross_margin,Q2 2025,snapshot and standalone report agree
17,info,MediSight_Q2_2025.pdf,MediSight,headcount,Q2 2025,snapshot and standalone report agree
18,info,MediSight_Q2_2025.pdf,MediSight,revenue,Q2 2025,snapshot and standalone report agree
19,info,NovaCloud_Q2_2025.pdf,NovaCloud,arr,Q2 2025,reported in 2 sources ['NovaCloud_Q2_2025.pdf'...
20,info,NovaCloud_Q2_2025.pdf,NovaCloud,cash,Q2 2025,reported in 2 sources ['NovaCloud_Q2_2025.pdf'...
11,info,MediSight_Q2_2025.pdf,MediSight,arr,Q2 2025,reported in 2 sources ['MediSight_Q2_2025.pdf'...
54,warning,MediSight_Q2_2025.pdf,MediSight,arr,Q2 2025,currency undetermined for monetary value '27.9M'
53,warning,MediSight_Q2_2025.pdf,MediSight,revenue,Q2 2025,currency undetermined for monetary value '6.8M'
52,warning,MediSight_Q1_2025.pdf,MediSight,arr,Q1 2025,currency undetermined for monetary value '26.1M'
51,warning,MediSight_Q1_2025.pdf,MediSight,revenue,Q1 2025,currency undetermined for monetary value '6.3M'
46,warning,ApexFreight_Q2_2025.pdf,ApexFreight,revenue,Q2 2025,conflicting labels mapped to same canonical me...
49,warning,FleetLink_Q4_2024.pdf,ApexFreight,revenue,Q4 2024,currency undetermined for monetary value '9.0M'
48,warning,CarbonTrack_Q2_2025.pdf,CarbonTrack,net_burn,Q2 2025,snapshot vs standalone disagree: {'snapshot': ...
47,warning,CarbonTrack_Q2_2025.pdf,CarbonTrack,NaN,Q2 2025,value '+ $0.2M' not found in source text (unve...
55,warning,MediSight_Q4_2024.pdf,MediSight,revenue,Q4 2024,currency undetermined for monetary value '6.1M'
50,warning,LendBridge_Q2_2024.pdf,LendBridge,NaN,Q2 2024,value '+${0.4}M' not found in source text (unv...
56,warning,MediSight_Q4_2024.pdf,MediSight,arr,Q4 2024,currency undetermined for monetary value '24.5M'

## Trace one number to its source

Pick any value in the pivot, find its row in `metrics_long.csv`, and open the source PDF
at the recorded page — the verbatim label is printed there. The verify step does this
string-match automatically for every extracted value.